# Generated by Django 6.0.2 on 2026-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
        ),
    ]
