# Generated by Django 6.0.2 on 2026-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie'),
        ),
    ]
