# Generated by Django 6.0.2 on 2026-03-06 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Association Jésus Miséricordieux', max_length=100, verbose_name='Nom du site')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configurations du site',
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle concerné')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'activité admin",
                'verbose_name_plural': "Logs d'activité admin",
                'ordering': ['-created_at'],
            },
        ),
    ]
