# Generated by Django 5.2.12 on 2026-03-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='file',
        ),
        migrations.CreateModel(
            name='ProgramContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='programs/')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='programs.program')),
            ],
            options={
                'ordering': ['-end_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramContentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='programs.program')),
            ],
            options={
                'ordering': ['start_date', 'end_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramContentScheduleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programs.programcontentschedule')),
            ],
            options={
                'ordering': ['start_time', 'end_time', 'id'],
            },
        ),
    ]
