# Generated by Django 6.0.2 on 2026-03-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type de bureau')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de bureau',
                'verbose_name_plural': 'Types de bureau',
            },
        ),
        migrations.CreateModel(
            name='MemberPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Poste')),
                ('description', models.TextField(help_text='Description du poste', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text="Définit l'ordre d'affichage des postes", verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('board_type', models.CharField(choices=[('diocesan', 'Bureau Diocésain'), ('decanal', 'Bureau Décanal'), ('parish', 'Bureau Paroissial')], max_length=20, verbose_name='Type de bureau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('doyenne', models.ForeignKey(blank=True, help_text='À remplir uniquement pour les bureaux décanaux', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parishes.doyenne', verbose_name='Doyenné')),
                ('parish', models.ForeignKey(blank=True, help_text='À remplir uniquement pour les bureaux paroissiaux', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parishes.parish', verbose_name='Paroisse')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, help_text='Brève biographie du membre', null=True, verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='parishes.parish', verbose_name='Paroisse')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.memberposition', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['position__order', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, help_text='Laisser vide si le mandat est toujours en cours', null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=True, help_text='Indique si ce mandat est actuellement en cours', verbose_name='Mandat actuel')),
                ('board_type', models.CharField(choices=[('diocesan', 'Bureau Diocésain'), ('decanal', 'Bureau Décanal'), ('parish', 'Bureau Paroissial')], help_text='Type de bureau pour ce mandat', max_length=20, verbose_name='Type de bureau')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='boards.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Mandat',
                'verbose_name_plural': 'Mandats',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board', verbose_name='Bureau')),
                ('mandate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_membership', to='boards.mandate', verbose_name='Mandat')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.member', verbose_name='Membre')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_memberships', to='boards.memberposition', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'unique_together': {('board', 'member', 'position')},
            },
        ),
    ]
