# Generated by Django 6.0.2 on 2026-03-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': 'Bureau', 'verbose_name_plural': 'Bureaux'},
        ),
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateField(blank=True, help_text='Laisser vide si le bureau est toujours actif', null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='board',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Indique si ce bureau est actuellement actif', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='board',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
