# Generated by Django 6.0.2 on 2026-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_options_board_end_date_board_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du mandat', null=True, verbose_name='Description du mandat'),
        ),
    ]
