# Generated by Django 6.0.2 on 2026-03-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='parishes.parish', verbose_name='Base/Paroisse')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('date', models.DateField(verbose_name="Date de l'événement")),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='histories.histories', verbose_name='Historique')),
            ],
        ),
    ]
